config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  get 'articles/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles do
    resources :comments
  end

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  def to_param
    "#{id}-#{title.parameterize}"
  end
  include Visible
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  before_create :set_name
  private
  def set_name
    self.commenter = 'anonymous' if commenter.blank?
  end
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  VALID_STATUS = ['public', 'private', 'archived']
  included do
    validates :status, inclusion: {in: VALID_STATUS}
  end

  def archived?
    status == 'archive'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_theme
  before_action :configure_permitted_paramters, if: :devise_controller?

  def set_theme
    if params[:theme].present?
      theme = params[:theme].to_sym
      # session[:theme] = theme
      cookies[:theme] = theme
      redirect_to(request.referrer || root_path)
    end
  end

  protected

  def configure_permitted_paramters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @articles = Article.includes(:user).order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def about; end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit('title', 'body', 'status')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = [hard_wrap: true, auto_link: true, fenced_code_blocks: true]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class= "form-group mt-3">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class= "form-group"><%= message %></div>
    <% end %>
  </div>

  <div class= "form-group mt-3">
    <%= form.label :body  %><br>
    <%= form.text_area :body, size: "60x10", class: "form-control" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<div> <%= form.label :status, class: 'form-label' %> <br> 
<%= form.select :status, ['public', 'private', 'archive'], selected: 'public', class: 'form-select' %>
</div>
  <div>
    <%= form.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-danger ps-5 d-flex " style="background: #ce1e1e; font-sans-serif">
  <%= link_to 'Agbablogrs', root_path, class:"navbar-brand fw-bold fs-4 logo text-white fw-bold w-50"%>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> <div class=" flex-grow-1 pe-5" id="navbarNav">
  <div >
    <ul class="navbar-nav">
      <li class="nav-item active">
  
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Write an Article ',  new_article_path, class:"nav-link logo text-white"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Profile ',  edit_user_registration_path, class:"nav-link logo text-white"%> 
      </li>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link logo text-white" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Write an Article',  new_article_path, class:"nav-link logo text-white"%>
      </li>
      <li>
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link logo text-white"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class:"nav-link logo text-white"%>
      </li></div>
      <% end %>
  </div>
</nav>

app/views/articles/about.html.erb
<h1>About us</h1>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<% if user_signed_in? %>
<%= render "form", article: @article %>
<% end %>

app/views/articles/index.html.erb
<h2 class = "text-center fw-bold mt-4 font-monospace">Latest Articles</h2>
<% @articles.each do |article| %>
<% unless article.archived? %>
<div class=" mx-auto">
  <div class="jumbotron jumbotron-fluid border m-2 p-2">
    <div class="container">
    <h2 class=" text-capitalize "><%= link_to(article.title, article, 
    class:"text-decoration-none text-inherit", style: "color: #27c5ca;") %></h2>
      <small class="d-block mx-2 lead">
        <%= article.body %> 
        <%= link_to('Read More', article, class: 'link-info text-break')  %>
      </small>
      <p class=" mx-2"><small > Created at <%= article.created_at %> </small></p>
      <p class=" mx-2"><small > Created by <%=article.user.name %> </small></p>
    </div>
  </div>

 
</div>
<% end %>
<% end %>

app/views/articles/new.html.erb
<h1 class= "mt-5 fw-bold">New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1 class="m-2 yy"> <%= @article.title %></h1>
<p class="m-4"> <%= markdown(@article.body )%> </p>

<% if current_user == @article.user and user_signed_in?%>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary"> <%= link_to 'Edit Article',
   edit_article_path(@article), class: "btn btn-secondary"%> </button>
  <a  class="btn btn-danger"> <%= link_to 'Delete', article_path(@article), 
  data:{ turbo_method: :delete, turbo_confirm: 'Are you sure'}, class: "btn btn-danger" %> </a>
    
</div>
<% end %>

<hr/>
<figure class=" shadow" style="background: #8b828211;">
<p class="fs-2"> Comments </p>
<div class= "px-3">
  <% @article.comments.each do |comment| %>
  <blockquote class="blockquote">
    <p><%= comment.body %>.</p>
     <%= link_to "Delete Comment", [comment.article, comment], data:
     { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete the comment'}, class: "btn link-info float-end"  %>
  </blockquote>
  <figcaption class="blockquote-footer mx-3">
   <cite title="Source Title">
    <%= comment.commenter %></cite>
    

  </figcaption>
  <p><hr/></p>
  <% end %>
  </div>
  <%= render 'comments/form' %>
</figure>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
<div class= "form-group mx-auto w-50">

  <p>
    <%= form.text_area :body, class: "form-control", placeholder: "Add a new Comment" %>
  </p>

  <p >
    <%= form.text_field :commenter, class: "form-control", placeholder: "Name", size:"70x30" %>
  </p>

  <p >
    <%= form.submit class: "btn btn-success form-control border-2 "  %>
  </p>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <% notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" >
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
   
    <%= javascript_include_tag "application-esbuild", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  </head>

  <body class="<%= cookies[:theme] %>">
    
    <%= render 'articles/header' %>
    <div class = "container logo">
    <br/>
   <% if notice %><div class = 'alert alert-info'> <%= notice %> </div> <% end %>
    
    <% if alert %> <div class = 'alert alert-warning'> <%= alert %> </div> <% end %>
  <abbr title="Change theme">
  <% if cookies[:theme] == "light" %>
    <%= link_to "", root_path(theme: "dark"), class: " fs-3 text-dark bi bi-lamp-fill" %>
  <% else %>
    <%= link_to "", root_path(theme: "light"), class: "fs-3 text-light bi bi-lamp" %>
  <% end %>
  </abbr>
    
      <%= yield %>
    </div>

    <footer class = " hello bg-dark">
    <a href="#" class="text-decoration-none link-light mx-2"> <i class="fab fa-facebook-square"></i>
    
    </footer>
  </body>
</html>